MicrosoftDocs/WDAC-Toolkit

- WDAC-Policy-Wizard/app/src/BuildPage.Designer.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
Creating WDAC policies uses the -DriverFilesPath instead of scanning the entire directory and parsing the correct Driver. 
The result is much more accurate and fast rules/policies creation.
> Refactor scan

- WDAC-Policy-Wizard/app/src/EditWorkflow.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/Policy.cs
Fixed issue #8  by escaping all user input text in cmdlet command. Also fixed bug where policy ID changes in UI would not manifest in policy.
#8
> Fixed issue #8 - folder path rules would crash policy creation

- WDAC-Policy-Wizard/app/src/Helper.cs
- WDAC-Policy-Wizard/app/src/MainForm.Designer.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/PolicyMerge_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/PolicyMerge_Control.cs
Users can now select up to 100 policies at the same time without having to click "+ Add Policy" 100 times. Selecting the "+ Add Policy" button allows for multiple files to be selected. All files are checked against the current list of files to merge and added to the table. 
Users can also multi-deselect policies from the table to merge into their final merged policy. 
openFileDialog.Multiselect = true;
> Allow user to select all policies they wish to merge into one policy in the FileDialog Window

- WDAC-Policy-Wizard/app/src/MainForm.Designer.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
Fixed the following 3 bugs (RC + fix):
1. Workflow button (eg. Policy Creator underneath Home button) on the rhs control panel when hovered, shows it can be clicked. Clicking does not appear to do anything. Fix: changed object from WindowsForms.Button to WindowsForms.Label so it can no longer be clicked. 
2. Appearance of 2 "Creating Policy" buttons in the Policy Editor workflow. This would appear if the user began creating a policy, abandoned it and began editing a policy. Fix: Button 5 in the control panel is now set to Enabled=False in the editor and merger workflows. 
3. Settings page was inaccessible after creating, editing or merging a policy. Fix=ControlPanel() sets settingsPage.Enabled=True
> Bug fix control panel UI-UX

- WDAC-Policy-Wizard/app/src/BuildPage.cs
- WDAC-Policy-Wizard/app/src/EditWorkflow.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/Policy.cs
- WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
If the binary conversion setting is enabled, the Wizard will determine the naming convention of the compiled policy to either
- {PolicyGUID}.cip if multi-policy format is selected
- Schema path (user defined).bin if legacy format
Also showing the destination of the binary file on the final page to show the user where the binary file was placed.
> Multi format policy bins named {guid}.cip

- WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/src/SettingsPage.Designer.cs
- WDAC-Policy-Wizard/app/src/SettingsPage.cs
Fixed issue #25 where modifying the app settings, returning to home/workflow, and revisiting the settings page would overwrite/reset the settings and UI to their default states. 
Moved the location of the reset call, Properties.Settings.Default.Reset(), from onLoad() to the proper function, onReset(). 
Also refactored the settingsPage checkbox click code to one function per checkBox. It is cleaner that way.
> Fixed bug where settings were being reset every 2nd Settings page load.

- WDAC-Policy-Wizard/app/MSIX/AppxManifest.xml
- WDAC-Policy-Wizard/app/MSIX/RulesDict.xml
- WDAC-Policy-Wizard/app/MSIX/WDACWizard.appinstaller
- WDAC-Policy-Wizard/app/Properties/AssemblyInfo.cs
- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.Designer.cs
- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.cs
- WDAC-Policy-Wizard/app/src/EditWorkflow.cs
- WDAC-Policy-Wizard/app/src/Helper.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
**Custom Path Rules**
- Implemented support for macros, specifically, %OSDRIVE%, %WINDIR%, %SYSTEM32%
- Implemented support for wildcards at the front and end of paths, e.g. */foo/bar.exe and C:\foo\*
- Folder rules will replace C:\, C:\Windows and C:\Windows\System32\ with %OSDRIVE%, %WINDIR%, %SYSTEM32%, if the setting is enabled
**Custom Version and file name**
- Implemented support for arbitrary min and max versions. Min < Max version, and max version must be < 65355.65355.....
- Implemented support for arbitrary filename
**Custom SHA256 PE hash rules**
- Implemented support for arbitrary hash rules. Each hash must be 64 characters and comma separated
Before clicking the textbox - title disappears on click
> WDAC Wizard supports custom path, hash and version values for file rules

- WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.Designer.cs
- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.cs
- WDAC-Policy-Wizard/app/src/Helper.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
You can now create PFN rules based on plain text (i.e. the package does not need to be on the device). Simply select the "Use Custom Package Family", enter the name of the package in the text field and select the Create button. The Wizard will handle the rest. 
The Wizard supports many packages in one single rule. There is no need to append each package to the table, though this is also supported, but rather a bulk add to the table. In either case, the output of the Wizard is N number of custom PFN rules.
> The WDAC Wizard supports arbitrary package family name rules

- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.cs
- WDAC-Policy-Wizard/app/src/Exceptions_Control.cs
- WDAC-Policy-Wizard/app/src/PolicyMerge_Control.cs
- WDAC-Policy-Wizard/app/src/PolicyType.cs
- WDAC-Policy-Wizard/app/src/TemplatePage.Designer.cs
- WDAC-Policy-Wizard/app/src/TemplatePage.cs
…dle exception. Drive by renaming of functions
**Behavior:** Clicking 'Cancel' on the templates page when selecting a location to save the policy results in an unhandled exception. 
**Solution:**Added exception handling for OpenFileDialog and SaveFileDialog when a user may select **Cancel** which returns an empty string by the helper function. Quick refactoring of method names
Fixed issue #79
> User selecting Cancel during OpenFile crashes the wizard

- WDAC-Policy-Wizard/app/src/BuildPage.Designer.cs
- WDAC-Policy-Wizard/app/src/BuildPage.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/PolicyMerge_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/PolicyMerge_Control.cs
- WDAC-Policy-Wizard/app/src/PolicyMerge_Control.resx
**Behavior:** The Wizard may reset the policy ID during the merge workflow. 
**Root cause:** The bug stemmed from a non-null set of custom rules after building a new policy, then going to the merge policy workflow. 
**Solution:** Reset this.Policy object at the end of build policy. 
Closing #87
> WDAC Wizard resets final policy ID during merging policies

- WDAC-Policy-Wizard/app/MSIX/Empty_Supplemental.xml
- WDAC-Policy-Wizard/app/src/ConfigTemplate_Control.cs
- WDAC-Policy-Wizard/app/src/Helper.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/Policy.cs
- WDAC-Policy-Wizard/app/src/PolicyType.cs
New supplemental policy workflow: 
- Supplemental policies are based off an empty supplemental instead of the base policy to supplement
> Fixed issue #103 where new supplemental policies inherited all rules from the base

- WDAC-Policy-Wizard/app/src/EventLog.cs
- WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.Designer.cs
- WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.cs
Fixed the following broken experience - 
1. An event with >1 correlated signing events would only show 1 signer event in the table
2. Publisher="Unknown" signing events now are filtered out by the Wizard and not shown to the user
3. Previous commit (#118) broke event sorting in the DataGrid, specifically the event/trigger for EventRowClick(). Fixed sorting experience
4. Also added the ability for a user to move through the table using arrow keys. Now hovering over a row or clicking a row will update the fields in the rule creator UI
> Event log table report fixes

- WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/src/EditWorkflow.Designer.cs
- WDAC-Policy-Wizard/app/src/EditWorkflow.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
Users can now override the default save location for the policy under edit. The save location is optional so an empty save location will result in the current behavior. 
Addresses feature request #126
> Added optional save location to edit page

- WDAC-Policy-Wizard/app/src/ConfigTemplate_Control.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/Policy.cs
- WDAC-Policy-Wizard/app/src/PolicyType.Designer.cs
- WDAC-Policy-Wizard/app/src/PolicyType.cs
Added a check to determine if rule number 6 is already in the policy or policy template before setting it to prevent duplicate instances. 
Fixes issue #150
> Fixing the duplicate unsigned SI policy rule option bug

- WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.cs
- WDAC-Policy-Wizard/app/src/Helper.cs
Any time a custom user mode publisher rule is created: 
- New or edit policy workflow
- Event log creation workflow
these changes will automatically add the signer ID to the CiSigners section so the signer can pass the enterprise signing requirements
Closing issue #161
> Add CiSigner references for all custom publisher rules

- WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/src/EditWorkflow.Designer.cs
- WDAC-Policy-Wizard/app/src/EditWorkflow.cs
- WDAC-Policy-Wizard/app/src/EventLog.cs
The Wizard would parse Applocker .evtx files but not the AppLocker/Script and MSI log on the system if "system event" was selected. 
The changes include: 
- Parsing AppLocker events regardless of which option is selected
- Minor UI updates to show that AppLocker/MSI and Script are now being parsed and all the file paths of the evtx being parsed
Addresses request #156
> Parse system AppLocker events by default

- WDAC-Policy-Wizard/app/src/ConfigTemplate_Control.cs
**Before the change,** all rule options for supplemental policies under edit could be modified. 
**With the change,** only valid supplemental rule options can be modified. This is akin to the new supplemental policy workflow. 
Addresses issue #155
> Updated the rule-options UI/UX for edit policies

- WDAC-Policy-Wizard/app/src/Helper.cs
The issue was in the new helper method to add file rule references to the signing scenario. There was a bug in the loop causing multiple file rule references to be omitted from the signing scenario and dropped from the final policy
Closing #173
> Fixed bug where the Wizard would drop file rules

- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.cs
- WDAC-Policy-Wizard/app/src/Helper.cs
The Wizard has been creating rules using the unaltered file version from the FileVersionInfo API. When ISV and IHV partners malform the version info, the Wizard will create the rule with junk in the MinimumFileVersion field causing the compiler to complain during conversion to policy binary. 
This fix uses the 4 FileVersion parts and concatenates them together to create a string that is supported in the WDAC compiler. 
Some examples: 
1. "5.2.12-26" --> **5.2.12.26**
2. "6.1.7600.16385 built by: WDK_6001.18001" --> **"6.1.7600.16385**
Closing #178
> Reading the file version from the FileVersionInfo parts

- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.cs
Fixed bug #185 by checking if the rule is a publisher rule before updating the label text
Closes #185 
From this (bug):
**to this (expected):**
> Bug Fix: Wrong label would appear when user toggled the custom value checkbox on the customer rule panel

- WDAC-Policy-Wizard/app/src/MainForm.cs
1. No default fallback during folder scan. Set the default to Hash if not a single fallback is set
2. Duplicate rule-options. Removed the rule options from the folder scan resulting policy.
> Fixed bugs related to folder scan

- WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.cs
- WDAC-Policy-Wizard/app/src/Exceptions_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/Exceptions_Control.cs
- WDAC-Policy-Wizard/app/src/Exceptions_Control.resx
- WDAC-Policy-Wizard/app/src/Helper.cs
The allow and deny signer exceptions workflow was completely broken. Closing #184 
Exceptions can be created from: 
1. File attributes
2. File path 
3. File hash
Ex. File attributes are multi-selectable and accept custom values
These changes also added a check for rule in progress workflow: 
**Asserts that file path rules can not except a signer rule:**
> Implemented Signer exceptions workflow

- WDAC-Policy-Wizard/app/App.config
- WDAC-Policy-Wizard/app/MSIX/WDAC Wizard.exe.config
- WDAC-Policy-Wizard/app/Properties/Settings.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Settings.settings
- WDAC-Policy-Wizard/app/src/SettingsPage.cs
Closing #192 
Root cause:
There was a stale setting trying to be set on the page. 
The setting has since been removed from the config file so it will not be set. Also added a check if we cannot find a setting, break from trying to set it.
> Fixed NullException on Settings Page

- WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/src/EditWorkflow.cs
Closes #197 
A Wizard user was not selecting a single source for the event logs which resulted in the wizard hitting a "ArgumentOutOfRangeException" error. 
Added a check to the edit workflow so the Wizard will not advance to the software table to create rules if the Wizard never parsed an event log.
> 197 wizard throws an error after edit page if nothing is selected

- .gitignore
- AppLocker-Policy-Converter/app/AppLocker-Policy-Converter/AppLocker-Policy-Converter/AppLocker-Policy-Converter.csproj
- AppLocker-Policy-Converter/app/AppLocker-Policy-Converter/AppLocker-Policy-Converter/Helper.cs
- AppLocker-Policy-Converter/app/AppLocker-Policy-Converter/AppLocker-Policy-Converter/Program.cs
Fixed a couple of bugs: 
1. Empty applocker rule collections, eg. DLL, would cause the tool to exit early without converting other non-empty rule collections further down in the policy. 
2. Fixed filepath rule conversions where - 
2.1. Unsupported macros like %PROGRAMFILES%\* 
2.2. Rules where there are 1 wildcards in the middle of the path: 
E.g. %WINDIR%\Folder1\*\FolderX\tool.dll --> "*\FolderX\tool.dll"
This way, the intended binaries are still allowed/blocked without being too permissive E.g. %WINDIR%\Folder1\*
3. Fail all rules with more than 1 wildcard in the path
4. "Beautified" the tool output by grouping all the warnings and errors and dumping them at the end of program:
> Filepath rules and empty applocker rule collection bug fixes

- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/Policy.cs
Closing #203 
Bug where the filenames of policies under edit are being truncated:
Fixed the off by one bug. Also fixed the logic for version updates. Prior to the update, '9' was the highest integer supported in the Wizard so updated versions would follow:
10.0.0.9 --> 10.0.1.0
Now, the Wizard supports up to 2^16 UINT16 MAX:
10.0.0.9 --> 10.0.0.10
10.0.0.65535 --> 10.0.1.0
> Fixed the version update logic for policies under edit

- WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.cs
- WDAC-Policy-Wizard/app/src/Helper.cs
Added checks in the Wizard to detect when a file signed by any of the following. These algos are not supported in WDAC and will fail at the time of policy creation. Exposing the warning/error to the user so they know to select another rule type:
{ "1.3.132.0.34", "ECC_P384" },
{  "1.3.132.0.35", "ECC_P512" },
{  "1.2.840.10045.3.1.7", "ECC_P256" },
{  "1.2.840.10045.4.1", "ECDSA_SHA1" },
{  "1.2.840.10045.4.3", "ECDSA_SPECIFIED" },
{  "1.2.840.10045.4.3.2", "ECDSA_SHA256" },
{  "1.2.840.10045.4.3.3", "ECDSA_SHA384" },
{  "1.2.840.10045.4.3.4", "ECDSA_SH512" }
**UI shown to user:**
Tested using multiple ECC-signed files. Compared against RSA-signed files.
Closing #181
> Added unsupported crypto check

- WDAC-Policy-Wizard/app/src/AdvancedHunting.cs
- WDAC-Policy-Wizard/app/src/EventLog.cs
1. Fixed a bug causing unsigned files, files without a corresponding 3089, not to be shown to the user. 
2. Fixed a bug causing duplicate events (same hash, same folderpath, same policy auditing/blocking) to be shown to the user. Fixed this issue by correctly checking each hash (byte[]) value using a1.SequenceEqual(a2). Before, was trying to use "==" which always returned false
3. Fixed an issue where null hash values (byte[]'s) could cause a null exception and crash the app
> Bug Fix - MDE AH Parsing is not showing unsigned files

- WDAC-Policy-Wizard/app/src/Helper.cs
- WDAC-Policy-Wizard/app/src/SigningRules_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
Fixed bug where the filepath in the table and friendly name: 
Closing #219 
It now shows:
> Fixed bug where path was not displayed in the table

- WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/src/BuildPage.Designer.cs
- WDAC-Policy-Wizard/app/src/BuildPage.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
Closing #211 
This PR adds UI/UX for users to distinguish when Bin conversion failed. Also added the ability for the binary folder path to be opened in explorer when the label is selected. 
1. XML file cannot be opened UI:
2. XML or bin directory encountered an error trying to open UI:
3. Binary policy label is now clickable. Explorer will launch and open the directory where the CIP is contained -
> Updated the build page and messages when cip/xml cannot be opened

- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/src/Helper.cs
Closing #210 
1. Fixes an issue with creating "SignedVersion" publisher rules with a file attribute with only version information. The compiler does not view a file attribute with only version (max and min) as enough to qualify a rule. 
Added FileName="*" in this case just like the -Level SignedVersion in the powershell cmdlets do
2. Also did a driver by fix where FilePublisher rules with custom CN, filename or version info would ignore linked exception rules.
After the fix - 
<FileAttrib ID="ID_FILEATTRIB_A_0_0_0" FriendlyName="Allow files based on file attributes: 10.0.25309.1002" FileName="*" MinimumFileVersion="10.0.25309.1002" />
<Deny ID="ID_DENY_EX_0_0_0" FriendlyName="Deny files based on file attributes: 16.1.20399.201" FileName="*" MinimumFileVersion="16.1.20399.201" />
> 210 invalid signed version rules

- WDAC-Policy-Wizard/app/src/MainForm.cs
- Updated the default save location from MyDocuments to AppDataLocal\Temp\WDACWizard 
- Updated the fallback for the save location to AppDataLocal when the IsUserWriteable check fails if the Wizard is not running as administrator and cannot write to the location
> 208 Event Log policy file not saved to system

- WDAC-Policy-Wizard/app/src/MainForm.cs
Fixes an issue where the WDAC Wizard would output XML and {guid}.cip when the user walked through the single policy format workflow. 
The issue was when custom rules were created and merged, the output policy format was always multiple policy format. 
The fix always sets the single policy format attributes like the legacy PolicyTypeID and clears the BasePolicyID and the PolicyID iff the format is single policy. 
Closing #235 
Tested by creating custom rules (signer, file path, hash, folder scan, COM, etc) as well as merging the recommended block rules. Single policy format is now always output
> Fixes Bug #235 - Wizard outputs multiple policy format when single policy is desired

- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/PolicyType.cs
1. Improved the check that the base being supplemented does not contain the legacy GUID
2. Force base and supplemental policies by type and set the PolicyTypeID to null
Tested by creating multiple supplemental and base policies and verifying they compile correctly.
> Fixed #241 where supplemental policies were not generating a CIP file

- WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.cs
#234 was reported after 0 AH event rules were created. Selecting Next resulted in an empty policy. Suggested that the Wizard add a check for 0 event rules created. 
Now when a user attempts to advance without any rules created, the Wizard will not advance and show the following UI:
Closing #234
> Added a check for zero rules created blocking advancement

- WDAC-Policy-Wizard/app/src/Helper.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
Added logic in the final step of the policy conversion to detect large runs of zeros and remove the the "_0_0_0_...." with a unique number. Works for file rules (allow, deny and fileattribute) as well as signers (AllowedSigner, denied signer, cisigner, update signer, supplemental signer). 
Examples/tests: 
ID_SIGNER_S_48_54_0_0_0_0_0_0 --> ID_SIGNER_S_48_54_1
ID_DENY_CBD_1_7_0_0_0_0 --> ID_DENY_CBD_1_7_89
ID_FILEATTRIB_SYSINFO_123_dfds_2132 --> stays as is
The threshold for the ID 'undesrcore limit' is 3 or "_0_0_0". Replaces the first instance of this string. 
Closing #247 
From: 
To:
> 247 some wdac policies after merge have large runs of zeros appended to their ids

- WDAC-Policy-Wizard/app/MSIX/EmptyWDAC.xml
- WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/Resources/EmptyWDAC.xml
- WDAC-Policy-Wizard/app/Resources/policyTemplates/EmptyWDAC.xml
- WDAC-Policy-Wizard/app/src/ConfigTemplate_Control.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/Policy.cs
- WDAC-Policy-Wizard/app/src/PolicyType.Designer.cs
- WDAC-Policy-Wizard/app/src/PolicyType.cs
Previously, the Wizard required a base policy XML to generate a corresponding supplemental policy. Closes #249 and adds the ability for a user to provide either the XML path or the base policy ID to generate a supplemental policy. 
The new UI on the supplemental policy creation page:
> Added ability to create supplemental policies from only a base ID

- WDAC-Policy-Wizard/app/src/ConfigTemplate_Control.cs
- WDAC-Policy-Wizard/app/src/Helper.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
Closes #253 and fixes 2 issues: 
1. Multiple duplicates of the same rule-option values e.g. 50 UMCI instances --> 1
2. Returning Home will overwrite the current value of the rule option state
> WDAC Wizard policy rule option clean up

- WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
Version 2.2 had a bug where friendly names for path rules were missing the path. That means that there are policies in the wild created by Wizard v2.2 that have 'bad' friendly names. Updated the rule table parsing logic to add in the path where it was otherwise omitted. The net is a rule like this goes from : 
to this:
> displays correct friendly name if the FN is missing the path

- WDAC-Policy-Wizard/app/src/EditWorkflow.Designer.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/SettingsPage.Designer.cs
- WDAC-Policy-Wizard/app/src/SettingsPage.cs
Fixed an issue where selecting the "Settings" button after building policy from AH or evtx could result in a crash writing to a closed  logger instance
> Fix null exception in settings page in event log workflow

- WDAC-Policy-Wizard/app/src/ConfigTemplate_Control.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
This issue was reported this morning by a customer who was attempting to edit their WDAC supplemental policy. The issue is that the Wizard is reading from the empty supplemental policy instead of their existing policy. Confirmed that this does not affect base policies under edit, just supplemental policies. 
The fix is pointing the Wizard at the template path, which is just a copy of the supplemental policy file in the temp folder of the AppData Local folder.
> Fixed bug in version 2.3.1.0 where supplemental polices under edit do not show any rules

- WDAC-Policy-Wizard/app/src/AdvancedHunting.cs
**The Issue:**
This issue impacts apps signed by certificates with a comma in either the Issuer Name or Publisher name. E.g. Zoom which is signed by CN="Zoom Communications, Inc.". The comma in the CN causes the CSV parsing library to error on these entries and drop the 3089 rows. This causes the Wizard user to see empty/null signing info for signed files in the Advanced Hunting Flow. 
**The Fix:** 
1. Before parsing, look for all instances of a comma in the issuer CN or publisher CN. They will be identifiable as the CN will be wrapped in quotes eg. DEADBEEF,Digicert Signing Root CA 2023, "Zoom Communications, Inc.",,,DEADBEEF
2. Replace the "," in the quoted field with _#C#_: "Zoom Communications, Inc." --> "Zoom Communications#C# Inc."
3. Remove the quotes from the fields: "Zoom …
> 273 mde ah parsing cannot handle extra in publisher names like zoom inc

- WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/src/ConfigTemplate_Control.cs
- WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
The Issue:
Version 2.3.1.1 introduced a bug where new supplemental policies would inherit the entire set of file and signature rules from the base policy it is extending in the UI and the resulting XML. 
The Fix: 
This changes ensures the new policy - supplemental flow sets the Template Path attribute to none to prevent merging. The UI table parsing code is now forced to read the Empty_Supplemental.xml file as well. 
Tested: 
1. New Base policy creation
2. New supplemental policy creation flow
3. Editing base and supplemental policy flow
Closes #270
> Fixed supplemental policy inheriting rules from base policy issue

- WDAC-Policy-Wizard/app/src/Helper.cs
**Issue:**
The feature introduced into 2.3.1.1 to update IDs with long runs of zeros caused collisions between rule IDs. 
E.g. Scenario - 
ID_FILEATTRIB_ATILLK_2_1_0_0_0_0_0_0_0 becomes ID_FILEATTRIB_ATILLK_2_1
which collides with an existing ID: ID_FILEATTRIB_ATILLK_2_1
**Fix:**
Now the Wizard checks the proposed ID against the entire list of IDs in the policy and loops through possible IDs until finding a unique one
ID_FILEATTRIB_ATILLK_2_1_0_0_0_0_0_0_0 becomes ID_FILEATTRIB_ATILLK_2_2 if there is already a ID_FILEATTRIB_ATILLK_2_1
Closes #287
> Fixed deduplication logic in helper function and run against test XML

- WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/src/BuildPage.Designer.cs
- WDAC-Policy-Wizard/app/src/BuildPage.cs
- WDAC-Policy-Wizard/app/src/ConfigTemplate_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/ConfigTemplate_Control.cs
- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.Designer.cs
- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.cs
- WDAC-Policy-Wizard/app/src/EditWorkflow.Designer.cs
- WDAC-Policy-Wizard/app/src/EditWorkflow.cs
- WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.Designer.cs
- WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.cs
- WDAC-Policy-Wizard/app/src/Exceptions_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/Exceptions_Control.cs
- WDAC-Policy-Wizard/app/src/Exceptions_Control.resx
- WDAC-Policy-Wizard/app/src/MainForm.Designer.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/Policy.cs
- WDAC-Policy-Wizard/app/src/PolicyMerge_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/PolicyMerge_Control.cs
- WDAC-Policy-Wizard/app/src/PolicyType.Designer.cs
- WDAC-Policy-Wizard/app/src/PolicyType.cs
- WDAC-Policy-Wizard/app/src/SigningRules_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
- WDAC-Policy-Wizard/app/src/TemplatePage.Designer.cs
- WDAC-Policy-Wizard/app/src/TemplatePage.cs
Fixed a few issues found during testing:
- Build break
- Unsigned supplemental policies would not convert to binary
- Moved all the dark/light mode into the validated event handler as opposed to paint to prevent infinite loops
> Fixed build break and bug where unsign supp would not compile

- WDAC-Policy-Wizard/app/src/EditWorkflow.cs
- WDAC-Policy-Wizard/app/src/PolicyType.cs
- WDAC-Policy-Wizard/app/src/SettingsPage.cs
All of the background colors were recently changed to `Color.FromArgb(15, 15, 15)`. However, the labels/radioboxes on a few pages were still left as Black. This commit fixes the remaining labels/radioboxes background colors.
Example:
> DarkMode: Labels background color fix

- WDAC-Policy-Wizard/app/src/EditWorkflow.Designer.cs
- WDAC-Policy-Wizard/app/src/PolicyMerge_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/PolicyType.Designer.cs
- WDAC-Policy-Wizard/app/src/TemplatePage.Designer.cs
The text boxes were appearing with quite a jarring contrast in dark mode. I switched the text box BorderStyle to FixedSingle for a more visually appealing look with less contrast.
The text boxes in Custom Rule Conditions / Exceptions panel will need to be fixed in another commit.
Quick example:
> DarkMode: Lower contrast of text boxes

- WDAC-Policy-Wizard/app/src/BuildPage.cs
- WDAC-Policy-Wizard/app/src/EditWorkflow.Designer.cs
- WDAC-Policy-Wizard/app/src/MainForm.Designer.cs
- WDAC-Policy-Wizard/app/src/PolicyMerge_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/PolicyType.Designer.cs
- WDAC-Policy-Wizard/app/src/TemplatePage.Designer.cs
The mouseover highlights of the 3 main options as well as the menu options are geared more toward light mode. The contrast was too much for dark mode.
I kept the same DodgerBlue color and simply added a good amount of transparency so that it works well in both dark and light modes.
Also added a minor fix for Build page label background.
Screenshots:
> DarkMode: Lower contrast of mouseover highlights

- WDAC-Policy-Wizard/app/src/SettingsPage.cs
Fixes the behavior when unchecking the checkboxes on the Settings page.
I’m basically just making the checkbox background transparent on mouse click events.
This fix was requested in issue (https://github.com/MicrosoftDocs/WDAC-Toolkit/issues/309).
Please see comment (https://github.com/MicrosoftDocs/WDAC-Toolkit/issues/309#issuecomment-1752027704) for screen recording of my fix.
> Settings page fix for unchecking the checkboxes

- WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.Designer.cs
Similar to (https://github.com/MicrosoftDocs/WDAC-Toolkit/pull/304), this fixes the textbox contrast on the EventLogRuleConfiguration page.
> DarkMode: EventLogRuleConfiguration Textboxes

- WDAC-Policy-Wizard/app/src/SettingsPage.cs
**Issue:**
Switching between Light Mode and Dark Mode on the Settings page, the Reset button does not get the proper color based on the setting for light and dark mode. 
**Fix:**
Call the SetResetButtonColor method to force the painting of the button on 'Reset' as well as Settings Page loading.
> Fixed the reset button color

- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/SettingsPage.Designer.cs
- WDAC-Policy-Wizard/app/src/SettingsPage.cs
This commit sets a standard design for Dark Mode and Light Mode for the Next button on the MainForm and also the Reset button on the Settings page. There is also a standard MouseOverBackColor that fits the colors from the rest of the app.
Once some of other issues with Dark/Light Button Controls (https://github.com/MicrosoftDocs/WDAC-Toolkit/issues/313) are fixed, I would like to expand so that this button color standard is applied to all other buttons throughout the app.
**Examples:**
_These are animated gifs but don't seem to be animating unless you click on them._
> Set a standard design for Next and Reset buttons

- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.cs
- WDAC-Policy-Wizard/app/src/Exceptions_Control.cs
This commit brings Dark/Light Controls to TextBoxes and Comboboxes in the Custom Rules (Rule Conditions and Rule Exceptions) page. This also changes the default blank comboboxes to display `---Select---` by default to be more intuitive.
> DarkMode: Custom Rules - TextBoxes and Comboboxes

- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
**Issue**
Rules that were being removed in the edit workflow were only being removed from the UI, the old policy but NOT the policy the Wizard outputs. 
**Root Cause**
The Wizard was modifying the XML on disk from the old policy rather than the OutputPath. 
**Fix**
Updating the signing rules workflow to modify the "TemplatePath" which in turn gets converted to "OutputPath".
> Fixed policy rule removal bug during edit flow

- WDAC-Policy-Wizard/app/src/ConfigTemplate_Control.Designer.cs
This fixes the weird visual glitch when hovering the mouse over any of the toggles or also when clicking on them to change toggle state. Fixed by making MouseDownBackColor and MouseOverBackColor transparent.
This fix has been tested in both Light Mode and Dark Mode and fixes the visual glitch in both modes.
This fixes issue 3 in (https://github.com/MicrosoftDocs/WDAC-Toolkit/issues/309) reported by @HotCakeX
> ConfigTemplate: Toggle Fix

- WDAC-Policy-Wizard/app/src/SigningRules_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
This essentially keeps the button design the same as it was, but simply adds the same mouseover hover color as the other buttons.
> SigningRules: Standard Button Design

- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.Designer.cs
- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.cs
- WDAC-Policy-Wizard/app/src/Exceptions_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/Exceptions_Control.cs
Ensure Dark/Light Modes follow standard button design.
- CustomRuleConditionsPanel page and Exceptions_Control page (all buttons)
- adds Dark/Light modes control over enabled and disabled buttons
- fixed a few bugs/inconsistencies with Back and Next buttons
- included Light Mode comboBox fix from (https://github.com/MicrosoftDocs/WDAC-Toolkit/pull/323)
Screenshots:
> CustomRules: Standard Button Design

- WDAC-Policy-Wizard/app/src/PolicyType.Designer.cs
- WDAC-Policy-Wizard/app/src/PolicyType.cs
Ensure Dark/Light Modes follow standard button design.
Also fixed backColor of textBoxes.
> PolicyType: Standard Button Design

- WDAC-Policy-Wizard/app/src/TemplatePage.cs
Related to issue (https://github.com/MicrosoftDocs/WDAC-Toolkit/issues/307).
I think that the PictureBox MouseHover on the TemplatePage should be disabled for now until it can be fixed properly. Also, none of the other circular PictureBoxes throughout the app have the MouseHover effect anyway.
Temporarily disable MouseHover effect by changing FromArgb(190, 230, 253) to Transparent.
> TemplatePage: Temporarily Disable MouseHover

- WDAC-Policy-Wizard/app/src/ConfigTemplate_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.Designer.cs
- WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.cs
- WDAC-Policy-Wizard/app/src/EditWorkflow.Designer.cs
- WDAC-Policy-Wizard/app/src/EditWorkflow.cs
- WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.Designer.cs
- WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.cs
- WDAC-Policy-Wizard/app/src/Exceptions_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/Exceptions_Control.cs
- WDAC-Policy-Wizard/app/src/PolicyMerge_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/PolicyMerge_Control.cs
- WDAC-Policy-Wizard/app/src/PolicyType.Designer.cs
- WDAC-Policy-Wizard/app/src/PolicyType.cs
- WDAC-Policy-Wizard/app/src/SigningRules_Control.Designer.cs
- WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
- WDAC-Policy-Wizard/app/src/TemplatePage.Designer.cs
- WDAC-Policy-Wizard/app/src/TemplatePage.cs
1. Condensed the methods from #326 into a single method by passing in the button object to be manipulated
2. Fixed issue #307 by setting the back image instead of color
3. Fixed a bug where PCA textbox is not in dark mode
Before: ![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/23045608/aeb4078a-9a59-48b4-864b-6482b9ce8a93)
4. Fixed a bug where the textboxes were incorrectly colored when custom values were being used
Fix:![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/23045608/330dc0ea-5879-4b3b-8a4d-bb780517576a)
> Staging brach refactor

- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
**Issue**
Properly constructed WDAC policy with DeniedSigner with ExceptAllowRule would fail Wizard parsing resulting in dropping the entry from the Rules table. 
**Root Cause**
The parsing method was referencing the AllowedSigner.ExceptDenyRule instead of DeniedSigner.ExceptAllowRule, presumably due to a bad copy and paste. 
**Fix**
Replaced the bad reference and validated that the XML is correctly parsed
Closing #344
> Fixed XML Parsing Error with ExceptAllowRules

- WDAC-Policy-Wizard/app/src/AdvancedHunting.cs
Fixed 2 bugs reported by a WDAC Wizard user pertaining to MDE Advanced Hunting parsing - 
1. 8028/8029 events were not properly consumed by the Wizard
2. Customers who opt for local time, as opposed to ISO 8601 UTC times will not have their signing information events correlated 
The Wizard now supports local time by converting the timestamps to ISO 8601 e.g.  
**13/03/2024, 3:40:13.988 pm** is converted to **2024-03-13T06:40:13.9880000Z**
Fixes #349
> Add script events advanced hunting

- WDAC-Policy-Wizard/app/MSIX/SignedReputable - SingleFormat.xml
- WDAC-Policy-Wizard/app/MSIX/SignedReputable.xml
- WDAC-Policy-Wizard/app/Resources/policyTemplates/SignedReputable - SingleFormat.xml
- WDAC-Policy-Wizard/app/Resources/policyTemplates/SignedReputable.xml
Added the following rules to KMCI and UMCI signing scenarios: 
<EKU ID="ID_EKU_RT_EXT" Value="010a2b0601040182370a0315" FriendlyName="Windows RT WoA EKU - 1.3.6.1.4.1.311.10.3.21 Windows RT"/>
<Signer ID="ID_SIGNER_WINDOWS_FLIGHT_ROOT" Name="Microsoft Flighting Root 2014 Windows EKU">
<CertRoot Type="Wellknown" Value="0E" />
<CertEKU ID="ID_EKU_WINDOWS" />
</Signer>
<Signer ID="ID_SIGNER_ELAM_FLIGHT" Name="Microsoft Flighting Root 2014 ELAM EKU">
<CertRoot Type="Wellknown" Value="0E" />
<CertEKU ID="ID_EKU_ELAM" />
</Signer>
<Signer ID="ID_SIGNER_HAL_FLIGHT" Name="Microsoft Flighting Root 2014 HAL EKU">
<CertRoot Type="Wellknown" Value="0E" />
<CertEKU ID="ID_EKU_HAL_EXT" />
</Signer>
<Signer ID="ID_SIGNER_WHQL_FLIGHT_SHA2" Name="Microsoft Flighting Root 2014 WHQL EKU">
<CertRoot …
> Updated SignedReputable templates with Flight Root rules

- WDAC-Policy-Wizard/app/MSIX/DefaultWindows_Audit - SingleFormat.xml
- WDAC-Policy-Wizard/app/MSIX/DefaultWindows_Audit.xml
- WDAC-Policy-Wizard/app/Resources/policyTemplates/DefaultWindows_Audit - SingleFormat.xml
- WDAC-Policy-Wizard/app/Resources/policyTemplates/DefaultWindows_Audit.xml
**Issue**
Edge now packages an enclaves DLL signed by the new enclaves signer (special EKU + Root 2011). This signature is not default trusted in our Windows template so customers are seeing blocks/audits when running edge. 
**Fix**
Added the enclaves EKU + known root 07 (Root CA 2011) to the policy
> Added enclave signer to Default Windows policy and cleaned up EKU rules

- WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/WDAC Wizard.csproj
- WDAC-Policy-Wizard/app/src/AdvancedHunting.cs
- WDAC-Policy-Wizard/app/src/EditWorkflow.Designer.cs
- WDAC-Policy-Wizard/app/src/EditWorkflow.cs
- WDAC-Policy-Wizard/app/src/EventLog.cs
- WDAC-Policy-Wizard/app/src/Helper.cs
- WDAC-Policy-Wizard/app/src/LogAnalytics.cs
**What Changed**
Added support for parsing Log Analytics CSV files which the Windows Server team built. The Wizard supports a mix of MDE Advanced Hunting logs and Log Analytics csv files, or one of the other.
> Add log analytics parsing in the Wizard

- WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.Designer.cs
- WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.cs
- WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.resx
**Issue:**
Bug where filepath and folderpath checkboxes could not be unchecked resulting in file and folderpath rules created every time. 
**Fix:**
- Allow the checkboxes to be AutoCheck=true so users can un/check them
- Also right aligned the text in the 2 textboxes
> Allow file folder path checkboxes to be unchecked

- WDAC-Policy-Wizard/app/MSIX/EmptyWDAC.xml
- WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Resources.resx
- WDAC-Policy-Wizard/app/Properties/Settings.Designer.cs
- WDAC-Policy-Wizard/app/Resources/policyTemplates/EmptyWDAC.xml
- WDAC-Policy-Wizard/app/Resources/policyTemplates/Empty_Supplemental.xml
- WDAC-Policy-Wizard/app/WDAC Wizard.csproj
- WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.cs
- WDAC-Policy-Wizard/app/src/Helper.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
**Issues**
1. Policies created were generated with a GUID which collides with a Microsoft policy which causes issues deploying the policy
2. Policies are generated as Base Policies, which some folks didn't like
3. Policies were written to AppDataLocal, which some folks didn't like
**Fixes:**
1. Updated the EmptyWdac.xml GUIDs
2. Policies updated to Supplemental Policy type
3. Policies now written to Documents folder; fallback to Desktop path
Closing #370
> Fixed event log policy output

- WDAC-Policy-Wizard/app/src/AdvancedHunting.cs
- WDAC-Policy-Wizard/docs/using/advanced-hunting.md
Our MDE Advanced Hunting changes have been implemented and the Wizard can now parse the new fields!
**New fields include:**
OriginalFileName
InternalName
ProductName
FileVersion
FileDescription
EtwCorrelationId
The Wizard remains backwards compatible so correlation will fallback to the previously required timestamps, and none of the new fields are mandatory. This means that users can continue running their existing AH queries or use the new ones:
```
DeviceEvents 
| where ActionType startswith 'AppControlCodeIntegrity' 
// SigningInfo Fields
| extend IssuerName = parsejson(AdditionalFields).IssuerName
| extend IssuerTBSHash = parsejson(AdditionalFields).IssuerTBSHash
| extend PublisherName = parsejson(AdditionalFields).PublisherName
| extend PublisherTBSHash = …
```
> Added new AH fields!!

- WDAC-Policy-Wizard/app/MSIX/CreateSignerPolicy.ps1
- WDAC-Policy-Wizard/app/src/CreateSignerPolicy.ps1
**Issue:**
Rules set to Allow in the UI were created as Deny
Rules set to Deny in the UI were created as Allow
**Fix:**
Issue in the new PowerShell script which appended the -Deny flag if the Deny parameter == False. Fixed the logic
Closing #386
> Fixed incorrect logic in PowerShell script causing rule actions to be flipped

- WDAC-Policy-Wizard/app/src/EventLog.cs
- WDAC-Policy-Wizard/app/src/Helper.cs
**Issue:**
- In relation to Issue #382, it was discovered that Windows event log forwarding converts every field to strings. This caused parsing to fail where all hash fields (SHA1, SHA256 and file hashes) are encoded as byte arrays
- Additionally, I recognized that the existing parsing logic drops fields with empty strings (e.g. OriginalFilename, InteralName, etc.). This caused many out of bounds parsing errors
**Fix:**
- Updated event log parsing to use JSON string parsing which addresses both issues above. JSON string parsing allows for indexing all fields, regardless if they are null or empty
**Testing:**
- Tested against all EVTX files in test bank and the ForwardedEvent.evtx file added in the issue
> Updating event log parsing to use json

- WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.cs
**Issue:**
It was discovered that the Wizard will create 1 rule per 1 "+ Allow Rule" button select. 
Closing #395
**Fix:**
Prompt the user if a rule was already created. This allows the user to create a publisher rule, go back, and create a path rule, for example.
> Prompt user if the Add Allow Rule button was re-clicked

- WDAC-Policy-Wizard/app/src/CreateScannedPolicy.ps1
- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/PSCmdlets.cs
- WDAC-Policy-Wizard/app/src/PolicyHelper.cs
**Issue:**
- The folder scan operation (New-CiPolicy -ScanPath <>) was broken upon upgrade to dotnet core. In addition to New-CIPolicyRule parsing, it appears this scenario is incompatible on pwsh (.NET Core)
- Closing #297 
**Fix:**
- Addressed the bug by moving the folder scan operation into a ps1 file and executing it with the inbox PowerShell (5.x) version
- New-CIPolicy -ScanPath must be called twice as first call generates a "An item with the same key has already been added" WARNING. This causes only a subset of the file rules to be written to policy
- Also moved other PS commands like hash generation to the PS5 invocation method
> Fix Folder Scan by moving to PS5

- WDAC-Policy-Wizard/app/MSIX/AllowMicrosoft - SingleFormat.xml
- WDAC-Policy-Wizard/app/MSIX/AllowMicrosoft.xml
- WDAC-Policy-Wizard/app/MSIX/DefaultWindows_Audit - SingleFormat.xml
- WDAC-Policy-Wizard/app/MSIX/DefaultWindows_Audit.xml
- WDAC-Policy-Wizard/app/Resources/policyTemplates/AllowMicrosoft - SingleFormat.xml
- WDAC-Policy-Wizard/app/Resources/policyTemplates/AllowMicrosoft.xml
- WDAC-Policy-Wizard/app/Resources/policyTemplates/DefaultWindows_Audit - SingleFormat.xml
- WDAC-Policy-Wizard/app/Resources/policyTemplates/DefaultWindows_Audit.xml
- Dynamic code security still continues to log false positive error events. Removing from templates until this behavior is fixed. 
- Compiled policies to binary
- Verified the UI parses the policy and show Dynamic Code Security disabled
> Removed dynamic code security from templates

- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/PolicyHelper.cs
Received feedback the policies generated by scanning event logs should have unique policy ID, despite users having to update the BasePolicyID field anyway. 
Closing #392
> Update the policy ID at compilation time for event log policies

- WDAC-Policy-Wizard/app/src/MainForm.cs
**Issue:**
One user reported that the Wizard throws an error when attempting to merge the recommended blocklists with their new policy template. This could be a permissions issue with access to the ProgramFiles\WindwosApp directory which causes the PowerShell cmd to fail. 
**Fix:**
Instead of merging with the xml in the ProgramFiles\WindowsApp directory, copy the xmls out of the MSIX package to the temp folder and merge with the xmls in the temp folder instead
Closing #393
> Update Wizard to copy blocklists to and merge from temp folder

- WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.cs
- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/PSCmdlets.cs
The event log parsing workflow now converts event logs to supplemental policies with: 
1. Base Policy Id set to the most common policy ID in the audit/block events
2. A unique Policy Id
3. Parameters to convert a supplemental xml to cip
The Wizard now offers the ability to convert the xml to cip if the setting is enabled in the Settings Menu
> Convert supplemental xmls to binary policies to deploy

- WDAC-Policy-Wizard/app/src/Helper.cs
- WDAC-Policy-Wizard/app/src/PolicyHelper.cs
**Issue:**
EKU rules were not being added to new policies
**Fix:**
The new merge step did not merge the EKU rules so while the Signer had an EKU reference, the EKU section of the policy was missing the EKUs. Added in a merge EKU method
Also migrated off the obsolete method to calculate the ASN1 encoded value for EKUs. Now using the ASN1 API
> Fix bug in Wizard with EKUs

- WDAC-Policy-Wizard/app/src/PolicyHelper.cs
**Issue: **
Original filename in policy was being overwritten with '*' to protect against a bug in the compiler when only min or max version is set
**Fix:**
Fixed the check for null product, file description or original filename
Closing #421
> Fixed bug where Original Filename replaced with *

- WDAC-Policy-Wizard/app/src/EventLog.cs
**Issue:"**
3089 events with empty TBS hash values were successfully being created in the Wizard allowing for a user to generate a publisher or file publisher rule with an empty TBS hash and non-empty publisher name.
The policy successfully compiles but will fail to deploy with a generic CI failure. Bug filed in the OS to catch these failures in the compiler.
**Fix:**
Fail to create signer events if the TBS hash value is null/empty. 
Closes #434
> Remove empty or unknown signers from log files during policy editing

- WDAC-Policy-Wizard/app/App.config
- WDAC-Policy-Wizard/app/Properties/Settings.Designer.cs
- WDAC-Policy-Wizard/app/Properties/Settings.settings
- WDAC-Policy-Wizard/app/src/MainForm.cs
- WDAC-Policy-Wizard/app/src/PSCmdlets.cs
**Issue and Root Cause**
In some locked down environments, the Wizard fails to perform folder scanning (in PS 5) as the script execution policy does not permit 'untrusted scripts'. While the script is signed, the Microsoft Publisher is not trusted. 
**Fix:**
The Wizard will now try to add the Wizard signing certificate to the Current User's Trusted Publisher certificate store when running 1) Folder Scan - CreateScannedPolicy.ps1 and 2) Publisher and Hash rules - CreateSignerPolicy.ps1 
If the addition to the store fails, the user will be prompted to add it manually. The user can also suppress the prompts by selecting 'No' on the following dialog -
> Add Microsoft Publisher Certificate to Trusted Publisher Cert Store

- WDAC-Policy-Wizard/app/WDAC Wizard.csproj
Updated NuGet Dependencies. They aren't breaking changes because they're on the same Major.Minor versions (7.4.x.), and contain fixes for vulnerabilities.
> Updated NuGet Dependencies

- WDAC-Policy-Wizard/app/src/Helper.cs
**Issue:**
- Customer reports that their policy under edit (substring of policy_) is failing to update
- Root cause is the algorithm to generate unique file path collides with this naming convention and fails to find the int after "policy_"
**Fix:**
- Monotonically increasing counter to generate the policy filename 
Closes #456
> Updated unique policy filepath logic

- WDAC-Policy-Wizard/app/WDAC Wizard.csproj
- WDAC-Policy-Wizard/app/src/AdvancedHunting.cs
- WDAC-Policy-Wizard/app/src/EditWorkflow.cs
- WDAC-Policy-Wizard/app/src/LogAnalytics.cs
**Issue:**
- MDE and Log Analytics csv file schemas have changed over time. I wanted to support the current version of the schemas, but ensure that the parsing is backwards compatible. 
- FileHelpers is a terrible library for parsing CSV files. It claims to support OptionalFields, but it really does not
**Fix:**
- Spent the evening moving the Wizard's CSV parsing to the CsvHelpers library which supports more robust and reliable CSV file parsing in the face of data where some of the headers/columns are likely to be missing.
- Validated against 3 versions of MDE AH csv files and 3 versions of Log Analytics csv files (14.1, 14.2, 14.3)
- Validated against version 14.3.1 for Log Analytics. Version 14.4 is missing both sets of hashes and I won't support a hash-less CSV file, sorry @carlosmayol …
> Updated Advanced Hunting and Log Analytics CSV parsing to CsvHelpers

- WDAC-Policy-Wizard/app/src/PolicyHelper.cs
**Issue:**
During policy edit, the Wizard was creating new signer rules with duplicate IDs causing conversion to binary to fail. 
The issue was isolated to edits where Publisher rules were only being generated, i.e. not a single file attribute rule was created. The root cause was a bad perf improvement check in the method `FormatSignerRuleIDsAgainstExsiting` that was only checking for `FileRules` and not `Signers`. When `FileRules` were empty, the Wizard would break early and signer IDs were not compared. 
**Fix:**
Fixed the bad perf check to look at the `Signers` structure instead. 
A special thanks to @davideverall, @msgerbs, @jpkool, @tom-selby, @pranay-hinge who all helped root cause by providing repro steps. 
Closing #431
> Fixed duplicate Signer ID bug
