WDAC-Policy-Wizard/app/src/MainForm.cs, WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
Added logic to check the min system requirements to run the cmdlets in the backend.
=> Cmdlet compat check

WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs, WDAC-Policy-Wizard/app/Properties/Resources.resx, WDAC-Policy-Wizard/app/src/SettingsPage.cs, WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
Added a dialog box which pops up and warns if one of the fields is NA so user can determine if they want to add the file rule to the table. Message does inform that there is a possibility that a file hash rule is created instead. 
Also fixed a bug where deleting custom policy rules crashed the app.
=> Added NA warns to user. Fixed delete custom rule bug too.

WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.Designer.cs, WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.cs, WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.resx, WDAC-Policy-Wizard/app/src/Helper.cs, WDAC-Policy-Wizard/app/src/MainForm.cs
- Implemented package app rule creation
- Ability to search and multi-select packages to allow/block list packaged apps
During search:
After selection:
=> Feature packaged app rules

WDAC-Policy-Wizard/app/src/Helper.cs
=> Fixed Wizard OpenFileDialog filter where not all file extensions are shown

WDAC-Policy-Wizard/app/MSIX/RulesDict.xml, WDAC-Policy-Wizard/app/src/ConfigTemplate_Control.cs, WDAC-Policy-Wizard/app/src/Helper.cs, WDAC-Policy-Wizard/app/src/MainForm.cs
=> Fixed treat revoked/expired as unsigned parsing bug

WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.Designer.cs, WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.cs, WDAC-Policy-Wizard/app/src/EditWorkflow.Designer.cs, WDAC-Policy-Wizard/app/src/EditWorkflow.cs, WDAC-Policy-Wizard/app/src/Program.cs
**Clearly distinguishes between using params from file VS using custom rules**
=> custom rules textboxes are more clearly Distinguished from non-enabled textboxes

WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs, WDAC-Policy-Wizard/app/Properties/Resources.resx, WDAC-Policy-Wizard/app/src/EditWorkflow.Designer.cs, WDAC-Policy-Wizard/app/src/EditWorkflow.cs, WDAC-Policy-Wizard/app/src/SigningRules_Control.Designer.cs, WDAC-Policy-Wizard/app/src/SigningRules_Control.cs, WDAC-Policy-Wizard/app/src/SigningRules_Control.resx
**Added the ability to multi-select in the table and remove multiple rows/rules at once**
The Wizard multi-threads this operation so the UI is actively updated while deleting multiples rules
Bug Issue #80
=> Added the ability to remove multiple rules/rows from the custom rules table

WDAC-Policy-Wizard/app/MSIX/AllowMicrosoft.xml, WDAC-Policy-Wizard/app/MSIX/DefaultWindows_Audit.xml, WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.cs, WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
1. Custom path rules was broken
2. Wizard would crash if deleting a null rule from the rule table 
3. Reved the template policies to be aligned with the inbox ones
=> Fix post-merge bugs found in Main after validations

WDAC-Policy-Wizard/docs/getting-started/install-process.md
It's not clear why a bit.ly link is used instead of an aka.ms/ or direct URL; I propose replacing this so that it's clear this site is legitimate.
=> Replace bit.ly link in install-process.md

WDAC-Policy-Wizard/app/App.config, WDAC-Policy-Wizard/app/Properties/Settings.Designer.cs, WDAC-Policy-Wizard/app/Properties/Settings.settings, WDAC-Policy-Wizard/app/src/Helper.cs, WDAC-Policy-Wizard/app/src/MainForm.cs, WDAC-Policy-Wizard/app/src/SettingsPage.Designer.cs, WDAC-Policy-Wizard/app/src/SettingsPage.cs
1. Permanently disables the upload of the log output from the WDAC Wizard. 
2. Changes to the Settings page to remove the toggle
3. Removed other helper methods
=> Updates to the local logging workflow

WDAC-Policy-Wizard/app/src/CustomRuleConditionsPanel.cs
=> Removes the rule type check to always get the signing information

.gitignore, WDAC-Policy-Wizard/app/App.config, WDAC-Policy-Wizard/app/MSIX/WDAC Wizard.exe.config, WDAC-Policy-Wizard/app/Properties/Settings.Designer.cs, WDAC-Policy-Wizard/app/Properties/Settings.settings
=> Revert showMultiplePolicy settings change

WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
Fixed 2 bugs related to removing rules from the policies which prevented the policy from being converted to binary:
1. Signers would not be removed from CiSigners section
2. Hash rules were not being removed successfully
=> Fixed rule deletion feature

WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
Fixed 2 out of bounds errors during rule deletion in the Wizard
Closing #244
=> 244 wdac wizard crash on multiple rule removal

WDAC-Policy-Wizard/app/src/Helper.cs
The Wizard now successfully creates publisher rules with EKU. 
**Fix**
The issue was in the policy creation steps. The signers object with the EKU values was being overwritten and never added to the SiPolicy object.
=> Fixed EKU rule generation. EKU rules are created now

WDAC-Policy-Wizard/app/src/MainForm.cs
The Wizard had the following logic for new signed policies:
If rule-option #6 was disabled, the Wizard would override the user's selection and force the policy to be unsigned in order to compile with 0 PolicySigners
The new behavior: 
If rule-option #6 is disabled, and a user wants a signed policy XML, the Wizard will not override the rule-option 6 setting set by the user. Instead, the Wizard will not compile the XML to binary if any of the following are true: 
1. 0 UpdatePolicySigners
2. 0 SupplementalPolicySigners IFF Supplemental policies is set in the rule-options
Since the Wizard does not support adding update or supplemental policy signers, the user must add those signers and compile the binary themselves. 
Closing #262
=> Updated handling of Signed Policy option set

WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.Designer.cs, WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.cs, WDAC-Policy-Wizard/app/src/Exceptions_Control.Designer.cs, WDAC-Policy-Wizard/app/src/Exceptions_Control.cs, WDAC-Policy-Wizard/app/src/PolicyMerge_Control.Designer.cs, WDAC-Policy-Wizard/app/src/PolicyMerge_Control.cs, WDAC-Policy-Wizard/app/src/SigningRules_Control.Designer.cs, WDAC-Policy-Wizard/app/src/SigningRules_Control.cs
Improved dataGridView visually for both dark mode and light mode and ensure consistency throughout all pages with dataGridView.
=> dataGridView UI Consistency (Dark and Light Mode)

WDAC-Policy-Wizard/app/src/TemplatePage.Designer.cs, WDAC-Policy-Wizard/app/src/TemplatePage.cs
Ensure Dark/Light Modes follow standard button design.
=> TemplatePage: Standard Button Design

WDAC-Policy-Wizard/app/src/EditWorkflow.Designer.cs, WDAC-Policy-Wizard/app/src/EditWorkflow.cs
Ensure Dark/Light Modes follow standard button design.
=> EditWorkflow: Standard Button Design

WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.Designer.cs, WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.cs, WDAC-Policy-Wizard/app/src/PolicyMerge_Control.Designer.cs, WDAC-Policy-Wizard/app/src/PolicyMerge_Control.cs
Fixes on EventLogRuleConfiguration and PolicyMerge Pages
- Standard button colors on both pages for Dark/Light modes (WIP on https://github.com/MicrosoftDocs/WDAC-Toolkit/issues/313)
- Theme (Dark/Light modes) ComboBox on EventLogRuleConfiguration page
=> Theme Fixes on EventLogRuleConfiguration and PolicyMerge

WDAC-Policy-Wizard/app/src/PolicyType.Designer.cs
Updated the substring on the policy type page related to policy limits:
=> Update WDAC policy limit information

WDAC-Policy-Wizard/app/src/EventLogRuleConfiguration.cs
The Wizard now sets the base policy ID to the most common policy ID parsed from the event logs. For instance, 
Policy ID                                                    | Number of audit/block events
---------------------------------------------------------------------------------
4f137d4d-58ec-478a-a8b7-f9000f8f27a4         | 1
f09aa1a9-ff0c-48a8-a169-34fe19e36f54           | 3
44551521-3564-459a-a4d9-17270a4e0846      | 6
44551521-3564-459a-a4d9-17270a4e0846 will be set as the base policy ID in the supplemental policy
Closing #140
=> Event log policies are now created with base policy from most common events

WDAC-Policy-Wizard/app/src/MainForm.cs, WDAC-Policy-Wizard/app/src/PolicyHelper.cs
**Issue:**
- The rule ID generation logic creates duplicate IDs
- Some of the duplicate IDs don't conform to the ID_SIGNER_[A-Z]_[A-Z0-9] and ID_FILEATTRIB_[A-Z]_[A-Z0-9] schema
**Fix:**
- The Wizard now checks the policy the rules are merging into
- If any of the custom policy rules match the existing policy rules, the Wizard iterates through IDs until it finds one not in the existing policy
**How Tested:**
- Ran through 20-30 different rules
Closing #417
=> Updated unique rule ID generation logic

WDAC-Policy-Wizard/app/Properties/Resources.Designer.cs, WDAC-Policy-Wizard/app/Properties/Resources.resx, WDAC-Policy-Wizard/app/WDAC Wizard.csproj
Fixed a notice message regarding file path rules with more than 1 wildcard characters in them.
=> Fixed a notice message related to wildcard file paths and made it clearer

.github/dependabot.yml
I've included helpful links as comments in the yaml file for reference to the configurations that are implemented. It keeps the NuGet packages, .NET SDK and GitHub Actions up to date and performs this check weekly.
Once updates are found, pull requests are created and your username is set as reviewer.
=> Created Dependbot config to keep everything up to date in the repository

WDAC-Policy-Wizard/docs/using/advanced-hunting.md
=> Fixed typo in Advanced Hunting Docs

WDAC-Policy-Wizard/docs/using/advanced-hunting.md
I have migrated the MDE Kusto query to Splunk search to be used by those who either do not have an MDE subscription or do not have an access to it but have a splunk deployment and windows logs are ingested into the Splunk.
=> Updated Advanced Hunting Documentation with Splunk Search query
